### createa attach
POST http://localhost:8081/v1/yu-attach/upload-create
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Barear eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iLCJST0xFX01PREVSQVRPUiJdLCJwcm9maWxlX2lkIjoxLCJ1c2VybmFtZSI6ImFzaWx1c3RvejM3QGdtYWlsLmNvbSIsInN1YiI6ImFzaWx1c3RvejM3QGdtYWlsLmNvbSIsImlhdCI6MTc1MzYyNDA1OSwiZXhwIjoxNzUzNzEwNDU5fQ.aYkBrCWaS00M0OfCRVJICN1kxkBJG2iGkkzaPPYxZXo9ptvvYdqTjDkx1bU5jCba89vstQSX7t7SNEmqATu-7g"

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="gullar.jpg"

< C:\Users\user\Desktop\Java_in_Project\gullar.jpg





### createa attach Buni bemaolo ishlat
POST http://localhost:8081/v1/yu-attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Barear eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iLCJST0xFX01PREVSQVRPUiJdLCJwcm9maWxlX2lkIjoxLCJ1c2VybmFtZSI6ImFzaWx1c3RvejM3QGdtYWlsLmNvbSIsInN1YiI6ImFzaWx1c3RvejM3QGdtYWlsLmNvbSIsImlhdCI6MTc1MzYyNDA1OSwiZXhwIjoxNzUzNzEwNDU5fQ.aYkBrCWaS00M0OfCRVJICN1kxkBJG2iGkkzaPPYxZXo9ptvvYdqTjDkx1bU5jCba89vstQSX7t7SNEmqATu-7g"

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="gullar.jpg"

< C:\Users\user\Desktop\Java_in_Project\gullar.jpg







### createa attach
POST http://localhost:8081/v1/yu-attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Barear eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iLCJST0xFX01PREVSQVRPUiJdLCJ1c2VybmFtZSI6ImFzaWx1c3RvejM3QGdtYWlsLmNvbSIsInN1YiI6ImFzaWx1c3RvejM3QGdtYWlsLmNvbSIsImlhdCI6MTc1MzU5NTg0MiwiZXhwIjoxNzUzNjgyMjQyfQ.JHvHDHtEwvVkp6TCZzrYElJ4mXo9zCaIKczSfejfYhH_cUKo1_QxJjOptG9yoWxAe_a-wdInH481gwdtnAxDxg"


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="banner.jpg"

< D:\Java_in_Project\banner.jpg






### createa attach
POST http://localhost:8081/v1/yu-attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="QuyoshPlusDengiz.jpg"

< C:\Users\user\Desktop\Java_in_Project\QuyoshPlusDengiz.jpg

### createa attach
POST http://localhost:8081/v1/yu-attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="MushukMusic.jpg"

< C:\Users\user\Desktop\Java_in_Project\MushukMusic.jpg



#< C:\Users\user\Desktop\Java_in_Project\gullar.jpg

### bu
#< C:\Users\user\Desktop\Java_in_Project\QuyoshPlusDengiz.jpg


#fffopen/fileName/{fileName}
### Open qilish
GET http://localhost:8081/v1/yu-attach/open/fileName/QuyoshPlusDengiz.jpg

###
GET http://localhost:8081/v1/yu-attach/open/fileName/gullar.jpg
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=
###
GET http://localhost:8081/v1/yu-attach/open/fileName/banner.jpg
//meniki Zo'r qildim
### File Id bilan
GET localhost:8081/v1/yu-attach/open/fileId/1d1ad610-5d70-4559-a54b-8ec82d10d1d2.jpg

### Open ustozniki 999ddf23-9f99-45dd-9ac6-79789822e2fd
GET localhost:8081/v1/yu-attach/open/fileId/1d1ad610-5d70-4559-a54b-8ec82d10d1d2.jpg

### Download
GET http://localhost:8081/v1/yu-attach/download/1d1ad610-5d70-4559-a54b-8ec82d10d1d2.jpg

### Pagination
GET http://localhost:8081/v1/yu-attach/paginationAll?page=1&size=3
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=

### Delete
DELETE http://localhost:8081/v1/yu-attach/delete/33a4ba30-614c-475a-a3c0-f0577ef99847
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=



