### Registration user

POST http://localhost:8081/api/auth/registration
Content-Type: application/json
#Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=
Authorization: Barear eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFzaWx1c3RvejM3QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDU1IiwiaWF0IjoxNzIxNzQ4MDU3LCJleHAiOjE3MjE4MzQ0NTd9.oWn0bPiYOon-FpA8yIYXfbZmGnPPFS3aAZ7zpu6jOXY
#createda jwt kerakmas

{
  "name": "Asilbek",
  "surname": "Coders",
  "username": "asilustoz37@gmail.com",
  "password": "12345"
}
###CREATE###Buishladi
POST http://localhost:8081/api/auth/registration
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=

{
"name": "Bobur",
"surname": "Jumaniyazov",
"username": "oshmat3@gmail.com",
"password": "a2222"
}

### Login
POST localhost:8081/api/auth/login
Content-Type: application/json

{
  "username": "asilustoz37@gmail.com",
  "password": "12345"
}
### Login
POST localhost:8081/api/auth/login
Content-Type: application/json

{
  "username": "oshmat3@gmail.com",
  "password": "a2222"
}
###Creeateda 2
POST http://localhost:8081/api/auth/registration
Content-Type: application/json
#createda jwt kerakmas

{
  "name": "KompotGilos+",
  "surname": "Kompotov+",
  "username": "KompotS1@gmail.com",
  "password": "12324"
}
### nurbekamatboyev@gmail.com "username": "safarov.shahz@gmail.com",
### registration/email/verification
###Login user
POST localhost:8081/api/auth/login
Content-Type: application/json

{
  "username": "KompotS1@gmail.com",
  "password": "12324"
}














###
GET http://localhost:8081/api/auth/registration/email/verification/eyJhbGciOiJIUzUxMiJ9.eyJjb2RlIjo1MDc0Niwic3ViIjoianVtYW5peWF6b3YuYm9idXJAbWFpbC5ydSIsImlhdCI6MTc1MDgyNTc0MCwiZXhwIjoxNzUwOTEyMTQwfQ.iLFG5SnJ18VOhNOgjzLqa-s0agG0350wRDYNtnIUqvttqQb2fzJGV26W1nIgDb8BsB2qkpqZO0bnd0MRPgPS8w
Content-Type: application/json

{
  "name": "Asilbek",
  "surname": "Coders",
  "username": "asilustoz37@gmail.com",
  "password": "12345"
}

### Email registration confirm
GET http://localhost:8081/api/auth/registration/eyJhbGciOiJIUzUxMiJ9.eyJjb2RlIjo1MDc0Niwic3ViIjoianVtYW5peWF6b3YuYm9idXJAbWFpbC5ydSIsImlhdCI6MTc1MDgyNTc0MCwiZXhwIjoxNzUwOTEyMTQwfQ.iLFG5SnJ18VOhNOgjzLqa-s0agG0350wRDYNtnIUqvttqQb2fzJGV26W1nIgDb8BsB2qkpqZO0bnd0MRPgPS8w


###Verification
POST http://localhost:8081/api/auth/registration
Content-Type: application/json





###Bu Meniki ekam Login
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "username": "oshmat3@gmail.com",
  "password": "a2222"
}



###> {% client.global.set("jwt", response.body.jwt); %} qilib {{jwt}} ni
###
#{
"username": "asilustoz37@gmail.com",
"password": "12345"
#}



###Login

GET localhost:8081/api/auth/registration/eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFzaWx1c3RvejM3QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDU1IiwiaWF0IjoxNzIxNzQ4MDU3LCJleHAiOjE3MjE4MzQ0NTd9.oWn0bPiYOon-FpA8yIYXfbZmGnPPFS3aAZ7zpu6jOXY
Content-Type: application/json

{
  "username": "asilustoz37@gmail.com",
  "password": "12345"
}



###Token va  malumotlar
http://localhost:8081/api/auth/registration/email/verification/eyJhbGciOiJIUzUxMiJ9.eyJjb2RlIjo1NzAzMSwic3ViIjoianVtYW5peWF6b3YuYm9idXJAbWFpbC5ydSIsImlhdCI6MTc1MDc0ODA1NSwiZXhwIjoxNzUwODM0NDU1fQ.-KNd3o6GrJpm62nkpt5txi6-_V3S8PyUEGWBx3zP2rLQ6GHIeouunc2l0I12VeGed0rsI2KzY3OzPceir43vpA
/registration/email/verification/


### Test request Person
POST http://localhost:8081/api/auth/test-request-person
Content-Type: application/json
Profile-Id : 3

{

}


###eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFzaWx1c3RvejM3QGdtYWlsLmNvbSIsInN1YiI6ImFzaWx1c3RvejM3QGdtYWlsLmNvbSIsImlhdCI6MTc1MzU0NjY3OSwiZXhwIjoxNzUzNjMzMDc5fQ.B768H0okCYBPC7EyXhVRR91pL42OMH9kKEpmSoa_kKEmk0Lralqx4Bggt-bERdKau-bdyPf-3shfVbVRXT8MAg"#
eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFzaWx1c3RvejM3QGdtYWlsLmNvbSIsInN1YiI6ImFzaWx1c3RvejM3QGdtYWlsLmNvbSIsImlhdCI6MTc1MzU0NjY3OSwiZXhwIjoxNzUzNjMzMDc5fQ.B768H0okCYBPC7EyXhVRR91pL42OMH9kKEpmSoa_kKEmk0Lralqx4Bggt-bERdKau-bdyPf-3shfVbVRXT8MAg"
#

### Login
POST localhost:8081/api/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "123456"
}


####LOGIN
#POST https://notifiy.eskiz.uz/api/auth/login
#Content-Type: application/json
#eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFzaWx1c3RvejM3QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDU1IiwiaWF0IjoxNzIxNzQ4MDU3LCJleHAiOjE3MjE4MzQ0NTd9.oWn0bPiYOon-FpA8yIYXfbZmGnPPFS3aAZ7zpu6jOXY

