###Create
POST http://localhost:8081/api/v1/category/create
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=

{
    "id": 1,
    "name": "Education"
}

###Create
POST http://localhost:8081/api/v1/category/create
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=


{
    "id": 2,
    "name": "Music"
  }

###Create
POST http://localhost:8081/api/v1/category/create
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=

{
"id": 3,
"name": "Gaming"
}

###Create asilga
POST http://localhost:8081/api/v1/category/create
Content-Type: application/json
Authorization: Basic YXNpbHVzdG96MzdAZ21haWwuY29tOjEyMzQ1

{
"id": 4,
"name": "Technology"
}


###Update //id sini beramiz
PUT http://localhost:8081/api/v1/category/admin/update/2
Content-Type: application/json

{
  "id": 2,
  "name": "Bunisyoq"
}
###Delete //id sini beramiz
DELETE http://localhost:8081/api/v1/category/admin/delete/3
Content-Type: application/json

### GEt List category
GET http://localhost:8081/api/v1/category/list-by-date
Content-Type: application/json
