

###Create
POST /comment-like/commentLike/{commentId}?status=LIKE
Authorization: Bearer <token>

###Remove
DELETE /comment-like/commentLike-delete/{{commentId}}
Authorization: Bearer <token>



###
GET /comment-like/commentLike/user
Authorization: Bearer <token>


###Admin
GET /comment-like/commentLike/user/{{userId}}
Authorization: Bearer <admin-token>


###
GET /comment-like/commentLikeDislike/{{commentId}}/count

###
GET /comment-like/commentLike/{{commentId}}/reaction
Authorization: Bearer <token>
