
###Create
POST http://localhost:8081/api/v1/comment/create-comment/{{videoId}}
Content-Type: application/json

{
  "content": "Zo'r video!"
}


###Update
PUT http://localhost:8081/api/v1/comment/update-comment/cmt123
Content-Type: application/json

{
  "content": "Ajoyib video!"
}

###get video-comment all
GET http://localhost:8081/api/v1/comment/video-by-comment/abc123?page=0&size=5


### get profileId commentALL
GET http://localhost:8081/api/v1/comment/profile-commentAll/5?page=1&size=8

###Get replies of commetn
GET http://localhost:8081/api/v1/comment/replies-comment/{{commentId}}

###Get allComment
GET http://localhost:8081/api/v1/comment/commentBall?page=1&size=10

###
GET http://localhost:8081/api/v1/comment/replies-info/{{commentId}}



