
###Create
POST http://localhost:8081/profile/playList/create
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=

{
  "name": "TEKSHIRUV ONE O",
  "description": "This is a test playlist",
  "channelId": "a6430d81-9d2d-42ed-8580-3e7afcfa2fc0",
  "status": "PUBLIC"
}
###Create
POST http://localhost:8081/profile/playList/create
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=

{
  "name": "TEKSHIRUV three O",
  "description": "FF expert test playlist",
  "channelId": "a6430d81-9d2d-42ed-8580-3e7afcfa2fc0",
  "status": "PUBLIC"
}
###Create
POST http://localhost:8081/profile/playList/create
Content-Type: application/json
Authorization: Basic YXNpbHVzdG96MzdAZ21haWwuY29tOjEyMzQ1

{
  "name": "Expert 1 asilga",
  "description": "testing PLAYLIST ",
  "channelId": "c7292c12-6fdc-4cc5-99c4-a0357837e1c5",
  "status": "PRIVATE"
}

###Create
POST http://localhost:8081/profile/playList/create
Content-Type: application/json
Authorization: Basic YXNpbHVzdG96MzdAZ21haWwuY29tOjEyMzQ1

{
  "name": "2 Expert asilga",
  "description": "testing PLAYLIST ",
  "channelId": "c7292c12-6fdc-4cc5-99c4-a0357837e1c5",
  "status": "PUBLIC"
}


###Delete
DELETE http://localhost:8081/profile/playList/04b38fff-c4ff-4c00-965d-bff3e2fe36c9
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=
###Delete
DELETE http://localhost:8081/profile/playList/f97780bd-5a40-4be5-bd10-83e4f4f22651
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=
###Delete
DELETE http://localhost:8081/profile/playList/feeefd41-99d6-447a-9d22-62af72ff8163
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=


###Update
PUT http://localhost:8081/profile/playList/update-user/157b5958-a700-47b1-8367-77dcccba8d58
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=

{
  "name": "TEKSHIRUV two O",
  "description": "This Strong expert",
  "status": "PUBLIC"
}
###Update
PUT http://localhost:8081/profile/playList/update-user/1fea5e6b-5bca-43c6-96f0-c0819ad4d2d4
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=

{
  "name": "Updated playlist name",
  "description": "Updated description",
  "status": "PRIVATE"
}

###ADMin Page
GET http://localhost:8081/profile/playList/pagination
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=



###Admin uyserID(plays) Authorization: Barear eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFzaWx1c3RvejM3QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDU1IiwiaWF0IjoxNzIxNzQ4MDU3LCJleHAiOjE3MjE4MzQ0NTd9.oWn0bPiYOon-FpA8yIYXfbZmGnPPFS3aAZ7zpu6jOXY
GET http://localhost:8081/profile/playList/by-user/2
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=

###Admin uyserID(plays)
GET http://localhost:8081/profile/playList/by-user-plays/1
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=

