

###Create
POST http://localhost:8081/api/v1/subscription/create
Content-Type: application/json
Authorization: Bearer <USER_TOKEN>

{
  "channelId": "ch123",
  "notificationType": "ALL"
}

###Update
PUT http://localhost:8081/api/v1/subscription/change-status
Content-Type: application/json
Authorization: Bearer <USER_TOKEN>

{
"channelId": "ch123",
"status": false
}

###
PUT http://localhost:8081/api/v1/subscription/change-notification
Content-Type: application/json
Authorization: Bearer <USER_TOKEN>

{
  "channelId": "ch123",
  "notificationType": "PERSONALIZED"
}


### user subcriptionList
GET http://localhost:8081/api/v1/subscription/my
Authorization: Bearer <USER_TOKEN>


###ADMIN userdagi Subscrion
GET http://localhost:8081/api/v1/subscription/user/5
Authorization: Bearer <ADMIN_TOKEN>
