
###Create
POST http://localhost:8081/api/v1/tag/create
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=

{
  "id": 1,
"name": "Technology",
  "nameUz": "Texnologiya",
  "nameRu": "Технология",
  "nameEn": "Technology",
  "orderNumber": 1,
  "key": "tech"
}

###
//{
//  "nameUz": "Sport",
//  "nameRu": "Спорт",
//  "nameEn": "Sport",
//  "orderNumber": 1,
//  "key": "sport"
//}
###
###Create
POST http://localhost:8081/api/v1/tag/create
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=

{
  "name": "News",
  "nameUz": "Yangiliklar",
  "nameRu": "Новости",
  "nameEn": "News",
  "orderNumber": 2,
  "key": "news"
}
###Create
POST http://localhost:8081/api/v1/tag/create
Content-Type: application/json

{
  "name": "News",
  "nameUz": "Yangiliklar",
  "nameRu": "Новости",
  "nameEn": "News",
  "orderNumber": 2,
  "key": "news"
}

###Create
POST http://localhost:8081/api/v1/tag/create
Content-Type: application/json
Authorization: Basic b3NobWF0M0BnbWFpbC5jb206YTIyMjI=

{
"id": 3,
"name": "Sport",
  "nameUz": "Sport",
"nameRu": "Спорт",
"nameEn": "Sport",
"orderNumber": 3,
"key": "sport"

}
###UPDATE
PUT http://localhost:8081/api/v1/tag/update/3
Content-Type: application/json


{
  "nameUz": "Yangiliklar",
  "nameRu": "Новости",
  "nameEn": "News",
  "orderNumber": 2,
  "key": "news"
}




###Delete
DELETE http://localhost:8081/api/v1/tag/delete/3

###ALL
GET http://localhost:8081/api/v1/tag/getAll

###LAng With All
GET http://localhost:8081/api/v1/tag/lang/EN


