###POST /api/video/{videoId}/view
#
#GET /api/video/{videoId}/views/count
#
#GET /api/playlist/{playlistId}/views/count
###create
POST http://localhost:8081/api/video/51da2012-6544-4a7f-bf95-d65f42575858/view
Content-Type: application/json
Authorization: Basic S29tcG90UzFAZ21haWwuY29tOjEyMzI0



###GET
GET http://localhost:8081/api/video/51da2012-6544-4a7f-bf95-d65f42575858/views/count
Content-Type: application/json
Authorization: Basic S29tcG90UzFAZ21haWwuY29tOjEyMzI0



###GET
GET http://localhost:8081/api/video/51da2012-6544-4a7f-bf95-d65f42575858/views/count
Content-Type: application/json
Authorization: Basic S29tcG90UzFAZ21haWwuY29tOjEyMzI0