
###Create
POST /video-like/likeVideo/{videoId}?status=LIKE
Content-Type: application/json
Authorization:

###
POST /video-like/likeVideo/{videoId}?status=DISLIKE


###
DELETE /video-like/likeVideo/{videoId} → like/dislike olib tashlaydi

###
GET /video-like/likeVideo/user → foydalanuvchining o‘ziga yoqqan videolari

###
GET /video-like/likeVideo/{videoId}/count → like/dislike sonlari