
###Create
POST https://localhost:8081/video-tag/add
Content-Type: application/json
Authorization: Basic S29tcG90UzFAZ21haWwuY29tOjEyMzI0

{
  "videoId": "b1a2c3d4-e5f6-7890-ab12-cd34ef567890",
  "tagId": 1
}

###Delete
DELETE https://localhost:8081/video-tag/remove
Content-Type: application/json
Authorization: Basic S29tcG90UzFAZ21haWwuY29tOjEyMzI0

{
  "videoId": "b1a2c3d4-e5f6-7890-ab12-cd34ef567890",
  "tagId": 1
}

###GEt videoTag-----{List}
GET https://localhost:8081/video-tag/{{videoId}}
Content-Type: application/json
Authorization: Basic S29tcG90UzFAZ21haWwuY29tOjEyMzI0

